name = "durable-objects"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
	{ name = "DEMO", class_name = "Demo" }
]

[[migrations]]
tag = "v1"
new_classes = ["Demo"]
